basket1 = {"Kiwi", "Mango", "Banana", "Mango", "Grapes"}
basket2 = {"Mango", "Guava", "Coconut", "Guava"}
print("basket1: ", basket1)
print("basket2: ", basket2)
basket1.add("orange")
print("Basket1 after adding orange", basket1)
common_fruits = basket1.intersection(basket2)
print("Common fruits in baskets", common_fruits)
import array as arr
fruit_counts = arr.array('i' ,[3, 5, 2, 4])
fruit_counts.insert(0,1)
fruit_counts.append(6)
print("Fruit counts after ading them", fruit_counts)
count_of_4 = fruit_counts.count(4)
print("Number of times 4 appeared", count_of_4)
fruit_counts.reverse()
print("Reversed fruit counts array", fruit_counts)
print("")
print("====CLASSS FRUIT ORGANIZATION BASKET====")
print("basket1", basket1)
print("basket2", basket2)
print("fruit_counts", fruit_counts)
print("common fruits", common_fruits)
print("=================================================")